version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:${ECLIPSE_MOSQUITTO_VERSION}
    networks:
      - tyk
    volumes:
      - ./deployments/mqtt/volumes/mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883
      - 9001:9001
  nodered:
    image: nodered/node-red:${NODE_RED_VERSION}
    networks:
      - tyk

    volumes:
      - ./deployments/mqtt/volumes/nodered/data/flows.json:/data/flows.json
    ports:
    - 1880:1880