services:
  backstage:
    image: tyk-demo-backstage:1.0
    build:
      context: ./deployments/portal-backstage
      args:
        - BACKSTAGE_NPM_TOKEN=${BACKSTAGE_NPM_TOKEN:?NPM access token is missing from Docker environment file .env - see deployment README.md}
    ports:
      - 3003:3003
      - 7007:7007
    volumes:
      - ./deployments/portal-backstage/volumes/backstage/app-config.yaml:/backstage/app-config.yaml
      - ./deployments/portal-backstage/volumes/backstage/tyk-catalog.yaml:/backstage/tyk-catalog.yaml
    networks:
      - tyk
    environment:
      - TYK_DASHBOARD_API_TOKEN=${TYK_DASHBOARD_API_ACCESS_CREDENTIALS:-set_by_bootstrap_script}
