modules:
  http_2xx_json:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      valid_status_codes: [200]
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_body_not_matches_regexp:
        - '{"status":"pass".*}'