modules:
  http_200_json_status:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      valid_status_codes: [200]
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_body_not_matches_regexp:
        - '"status"\s*:\s*"(ok|pass)"' # Accept "ok" or "pass", so can be used across Gateway, Dashboard and MDCB
      tls_config:
        insecure_skip_verify: true  # Disables certificate validation for self-signed cert used by Tyk Gateway 2
  http_200:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: ip4
      valid_status_codes: [200]
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
