pipeline {
    agent any

    environment {
    }

    stages {
        stage('test') {
            steps {
                echo "Building from ${env.BRANCH_NAME}"
                echo "dash pass is $(echo /var/jenkins_home/tyk/dashboard2-user-api-credentials)"
            }
        }
        stage('deploy') {
            when {
                expression { env.BRANCH_NAME == 'master' }
            }
            steps {
                echo "Deploying from ${env.BRANCH_NAME}"
                sh "chmod +x ./cicd/data/jenkins/tyk-sync"
                sh "./cicd/data/tyk-sync sync -d http://e2-tyk-dashboard:3000 -s $(echo /var/jenkins_home/tyk/dashboard2-user-api-credentials) -p ./cicd/data/tyk-sync"
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}