echo "This functionality is not implemented yet."

# echo "Streams - Validated PubSub"
# echo "Part 4: Displaying errors from the application log"
# echo "This script watches the Tyk Gateway application log for errors generated by the stream pipeline processor."
# echo "It will display the error message generated by the invalid request sent by script 3."

# docker logs -f tyk-demo-tyk-gateway-1 2>&1 | grep -E "@service=benthos.*path=root.pipeline.processors.1.catch.0"
