CREATE USER admin WITH ENCRYPTED PASSWORD 'secr3t';
CREATE DATABASE portal;
GRANT ALL PRIVILEGES ON DATABASE portal TO admin;
ALTER DATABASE portal OWNER TO admin;
GRANT ALL ON SCHEMA PUBLIC TO admin;
