# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: 1

datasources:
  - name: Loki
    uid: webstore-logs
    type: loki
    url: http://loki:3100
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceID":"(\w+)"'
          url: ''
          datasourceUid: webstore-traces
          matcherType: label
