---
version: '3.9'
services:
  users-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: users-subgraph
    entrypoint: ./services/graphql-subgraphs/users/server
    environment:
      - PORT=4201
    ports:
      - "4201:4201"
    networks:
      - tyk

  posts-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: posts-subgraph
    entrypoint: ./services/graphql-subgraphs/posts/server
    environment:
      - PORT=4202
    ports:
      - "4202:4202"
    networks:
      - tyk

  comments-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: comments-subgraph
    entrypoint: ./services/graphql-subgraphs/comments/server
    environment:
      - PORT=4203
    ports:
      - "4203:4203"
    networks:
      - tyk

  notifications-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: notifications-subgraph
    entrypoint: ./services/graphql-subgraphs/notifications/server
    environment:
      - PORT=4204
    ports:
      - "4204:4204"
    networks:
      - tyk
