version: '3.9'
services:

  users:
    image: zalbiraw/go-api-test-service
    container_name: users
    entrypoint: ./users/server
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
    networks:
    - tyk

  posts:
    image: zalbiraw/go-api-test-service
    container_name: posts
    entrypoint: ./posts/server
    environment:
      - PORT=4002
    ports:
      - "4002:4002"
    networks:
      - tyk

  comments:
    image: zalbiraw/go-api-test-service
    container_name: comments
    entrypoint: ./comments/server
    environment:
      - PORT=4003
    ports:
      - "4003:4003"
    networks:
      - tyk