---
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.52
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP receiver
      - "14269:14269"  # Health Check
    networks:
      - tyk

networks:
  tyk:
