# This file based on the work from
# https://landing.google.com/sre/workbook/chapters/alerting-on-slos/

groups:
  - name: tyk
    rules:
      - record: task:http_response_error_count
        expr: tyk_http_requests_total{response_code=~"5[0-9]{2}"}

      - record: task:http_response_total_count
        expr: tyk_http_requests_total{response_code=~"[0-9]{3}"}

      - record: task:http_response_error_rate
        expr: sum by (job,api_name) (rate(task:http_response_error_count[1m]))

  - name: slo_metrics
    rules:

      - record: job:slo_errors_per_request:ratio_rate10m
        expr: sum by (job,api_name) (rate(task:http_response_error_count[10m])) / sum by (job,api_name) (rate(task:http_response_total_count[10m]))

      - record: job:error_budget:remaining
        expr: (1 - job:slo_errors_per_request:ratio_rate10m) * 100