version: '3.8'
services:
  waf:
    image: owasp/modsecurity-crs:${WAF_VERSION}
    networks:
      - tyk
    ports:
      - "8500:80"
    environment:
      - PARANOIA=1
      - BACKEND=http://httpbin
    deploy:
      restart_policy:
        condition: any