pipeline {
    agent any

    environment {
        tyk2_dashboard_credentials = credentials('tyk2-dashboard-credentials')
    }

    stages {
        stage('deploy') {
            when {
                expression { env.BRANCH_NAME == 'master' }
            }
            steps {
                
                echo "Deploying from ${env.BRANCH_NAME}"
                sh "chmod +x tyk-sync"
                sh "./tyk-sync sync -d http://tyk2-dashboard:3000 -s ${env.tyk2_dashboard_credentials} -p ."
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}