---
name: Run linters
on: # yamllint disable-line rule:truthy
  - push

permissions:
  contents: read

jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          owner: TykTechnologies

      - name: Git - checkout pull request branch
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          fetch-depth: 1

      - name: Run yaml linter
        uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2  # master
        with:
          yamllint_file_or_dir: .
          yamllint_config_datapath: .yamllint.yaml
          yamllint_strict: strict
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ steps.app-token.outputs.token }}
