name: Windows and WSL2

on:
  push:

jobs:
  test-wsl2:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up WSL
      shell: powershell
      run: |
        wsl --update
        wsl --install -d Ubuntu
        wsl --set-default Ubuntu
        wsl --set-version Ubuntu 2
        
    - name: Install required tools in WSL
      shell: wsl-bash {0}
      run: |
        apt-get update
        apt-get install -y jq curl git
        
    - name: Verify Docker and Docker Compose v2
      shell: wsl-bash {0}
      run: |
        # Verify Docker
        docker --version
        
        # Verify Docker Compose V2
        docker compose version
        
        # Should show the v2 output format (not docker-compose)
        echo "Docker Compose V2 confirmed if previous command shows 'Docker Compose version v2.x.x'"
    
    - name: Run your scripts inside WSL
      shell: wsl-bash {0}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x *.sh
        
        # Run your script
        ./your-script.sh
        
        # If your script uses docker compose, you can verify it worked
        docker compose ps