name: Windows and WSL2

on:
  push:

jobs:
  test-wsl2:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Verify Docker and Docker Compose
      shell: powershell
      run: |
        docker --version
        docker compose version

    - name: Run up.sh script
      shell: bash
      run: ./up.sh
